item {
    id: 1
    name: 'bingo'
}

item {
    id: 2
    name: 'dtes'
}

item {
    id: 3
    name: 'hershey'
}

item {
    id: 4
    name: 'mysore sandal'
}

item {
    id: 5
    name: 'pepsodent'
}
